version: '3'
services:
  app:
    build: .
    ports:
      - "<outgoing port>:80"
    environment:
      - APIKEY=<SendGrid API key>
    volumes:
      - type: bind
        source: <path to the repository>/app
        target: /app/